version: '3.9'

services:
  backend:
    build: .
    ports:
      - "3000:3000"

    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    platform: linux/arm64/v8
    image: arm64v8/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - .env
